### ISSUE TITLE
wrong requirements.txt

### ISSUE THREAD

**Issue by miaomiao46** [SliencerX/Learning-to-Attack-Federated-Learning#1]
the versions in requirements.txt cause conflict when pip install

**Comment by SliencerX** [comment]
Hi,
Thank you for your interest in our work. I am not sure which packeges cause the conflict but I can tell the key packages are stable-baselines3(and pytorch with coresponding cuda toolkit) and more_itertools.  With these two packages installed you can try run the script to see if there are any more packages to install.
