### ISSUE TITLE
IndexError: index out of range in self in sim_train.py

### ISSUE THREAD

**Issue by ozturkoktay** [SliencerX/Learning-to-Attack-Federated-Learning#3]
Hi, 

When I try to run sim_train.py I get the following error:

```
dummy_batch = torch.index_select(
IndexError: index out of range in self
```

Could you please help me with this?

**Comment by SliencerX** [comment]
Hi,

I think change line 398 from ```500-1``` to ```200-1``` should solve the problem.

Best

**Comment by ozturkoktay** [comment]
Solved, thanks!
